### ISSUE TITLE
Issue: Recipe Not Added When Contributed

### ISSUE THREAD

**Issue by shouryamanekar** [Niyonyungu/CulinaShare#4]
# Issue: Recipe Not Added When Contributed

## Description
Contributors are facing an issue where the submitted recipe is not successfully added to the system.

## Steps to Reproduce
1. Navigate to the contribute page.
2. Fill out the required information for a new recipe.
3. Submit the form to contribute the recipe.
4. Observe whether the recipe is successfully added or not.

## Expected Behavior
Upon contributing a recipe, it should be added to the system and reflected in the recipe database.

## Actual Behavior
Recipes submitted through the contribute form are not being added to the system as expected.

## Environment
- Operating System: Windows
- Browser: Chrome

## Labels
- bug
- backend

**Comment by Niyonyungu** [comment]
When The Recipe is added you are redirected to the recipes page where you can see it , 
There is no backend for storing those , I am using local Data .
